### ISSUE TITLE
M0.2: Public Saturn L1 Nodes

### ISSUE THREAD

**Issue by patrickwoodhead** [filecoin-saturn/roadmap#1]
We will launch a public and trustless network of L1 nodes at FIL Lisbon. These L1 nodes will cache miss to the IPFS gateway. As a measure of success, we aim to have better performance than the IPFS Gateway.

We will pay L1 operators for their services, algorithmically in a centralized manner with basic anti-fraud detection, via log aggregation. This is not a block reward mechanism, just a payment system.

At this point, anyone who satisfies the L1 hardware requirements will be able to run an L1 node, contribute to the network, and earn Filecoin.

eta: 2022-11-30

**Comment by momack2** [comment]
Can you put "Saturn" in the title?

**Comment by quickhatche** [comment]
hey @patrickwoodhead checking on status since this still says open & ETA 11/2022
