### ISSUE TITLE
Convert Server Timings from L1s to OTEL spec in Caboose to enrich Honeycomb

### ISSUE THREAD

**Issue by reidlw** [filecoin-saturn/roadmap#16]
Can we add a flag that we send into Honeycomb so that we can partition data from trusted vs untrusted L1 nodes?

Should we have trusted L1s submit directly to Honeycomb rather than using Server Timings in Caboose?

**Comment by willscott** [comment]
@DiegoRBaquero - does the orchestrator currently return whether a node is core or not?
my understanding is that caboose does not know this currently

**Comment by DiegoRBaquero** [comment]
It's available passing `extraAttrs`: http://orchestrator.strn.pl/nodes?extraAttrs=core

**Comment by reidlw** [comment]
Waiting of deploy of bifrost 0.0.19. @willscott has pinged them in Slack.

**Comment by reidlw** [comment]
@willscott is this done?

**Comment by willscott** [comment]
we should have the 'is core' in honeycomb now, yes :+1:
