### ISSUE TITLE
Create a "runbook" for on call with lists of all metrics/alerts we are monitoring

### ISSUE THREAD

**Issue by reidlw** [filecoin-saturn/roadmap#22]
for lists of alerts/metrics, let's use the table Will put in the PRD: https://www.notion.so/pl-strflt/Saturn-Rhea-Observability-3ba02be6997b45d989758ca3de75ade4

probably best to convert this to Notion table and sync content across pages

let's maybe put thgis under on-call doc in notion

**Comment by joaosa** [comment]
This exists under [here](https://www.notion.so/pl-strflt/Saturn-Rhea-Observability-3ba02be6997b45d989758ca3de75ade4?pvs=4#64fdb37b46224442a56012b6b24e0557) and on Will's doc.
I'm thinking the actions column can be later expanded to link into specific runbooks.

Ideally, this should all be parsed from the alerts file. This way, we can even link the runbooks in the alert description.

**Comment by joaosa** [comment]
I'd say this is done. [Here](https://github.com/filecoin-saturn/terraform/tree/main/monitoring) are the instructions on how to update the alerts table which is linked both [here](https://www.notion.so/pl-strflt/Saturn-Alerts-5a312acfbe6f4a6e9305952f5d0a09ad) and [here](https://www.notion.so/pl-strflt/Saturn-Rhea-Observability-3ba02be6997b45d989758ca3de75ade4)
