### ISSUE TITLE
Lab Week launch plan 🚀 📈

### ISSUE THREAD

**Issue by reidlw** [filecoin-saturn/roadmap#24]
Overall labweek doc: https://www.notion.so/pl-strflt/lab-week-brain-exploding-aka-how-saturn-will-launch-at-lab-week-and-blow-minds-af61778837a749b28b0ec4e2246fbf63

**Comment by gruns** [comment]
https://www.notion.so/pl-strflt/lab-week-brain-exploding-aka-how-saturn-will-launch-at-lab-week-and-blow-minds-af61778837a749b28b0ec4e2246fbf63

**Comment by reidlw** [comment]
We're going to cover this during tomorrow's (9/20) daily meeting. Once team is on board, we can start creating issues for all the work needed
