### ISSUE TITLE
Big bets document

### ISSUE THREAD

**Issue by reidlw** [filecoin-saturn/roadmap#25]

**Comment by reidlw** [comment]
Reid/Ansgar to follow up with @prodalex on next steps here

**Comment by reidlw** [comment]
@prodalex is working on the requested 2-pager (has sent draft already) in the big bets channel.

**Comment by prodalex** [comment]
https://docs.google.com/document/d/1Xqo-6RTLHWeAiXu3n_CSoOwozN4_geX6c7vE_R_ZN3M/edit?usp=drive_link

**Comment by reidlw** [comment]
When are we meeting again with steering co.? @wilkyr31d and @prodalex to follow up with mroth
