### ISSUE TITLE
[PARENT - PORTAL] Saturn Portal

### ISSUE THREAD

**Issue by reidlw** [filecoin-saturn/roadmap#26]
ETA w/ Subvisual is - *roughly* - labweek

Design:
[x] Wireframes
[] Final UI - 80% complete

Development:
- [x] Authentication
- [x] Subscription logic
- [x] Service Worker Test
- [x] Test tiers set up
- [x] Integration with customer DB
- [x] Billing/Invoicing
- [x] Email Notifications of billing problems and such
- [x] UI
- [x] Input box for signup codes
- [ ] Staging Tests against customer requirements

Production:

- [x] Handover
- [x] #51
- [x] Final copy review
- [x] Tiers set up in Stripe
- [ ] Production Tests
- [x] #52
- [ ] #53

**Comment by gruns** [comment]
the title of this, `Saturn Portal`, is general. which items, or sub items, of the saturn portal is this issue tracking?

**Comment by reidlw** [comment]
- Subvisual working on back-end integration and UI
- Currently no sub-milestones to establish if we're on track. 
- Reid and Alex to meet to discuss if there's anything we can be using to measure progress along the way here

**Comment by prodalex** [comment]
Test app deployed (not final UI yet): https://saturn-portal.subvisual.com/sign-in

Design:
[x] Wireframes
[] Final UI - 80% complete 

Development:
[x] Authentication
[x] Subscription logic
[x] Service Worker Test
[x] Test tiers set up
[x] Integration with customer DB
[] Billing/Invoicing
[] Dashboard [IN Progress]
[] Notifications
[] UI
[] Staging Tests against customer requirements

Production:

[] Handover
[] Deployment
[] Final copy review
[] Tiers set up in Stripe
[] Production Tests

**Comment by hannahhoward** [comment]
we're now working on handover, possible assignment (needs further discussion) with @tchardin

**Comment by reidlw** [comment]
@tchardin and @joaosa are going to do the move to our AWS account and get prod deployment set up

**Comment by joaosa** [comment]
> @tchardin and @joaosa are going to do the move to our AWS account and get prod deployment set up

Is there a place where I can check the codebase in the meantime?

**Comment by hannahhoward** [comment]
@tchardin makes new repo and allows subvisual to push code, deployment after

**Comment by gruns** [comment]
repo is here: https://github.com/filecoin-saturn/portal

i gave them a seat and set up push permissions. theyll push the portal code there shortly

one decision to make: do we make the portal code open source or not. from PL pov? yes. from startup pov trying to make money? probably not.

> Is there a place where I can check the codebase in the meantime?

@joaosa great question. unfortunately not; they dont have any github seats either 😆. they couldnt (didnt want to) add anyone from saturn. lul

**Comment by reidlw** [comment]
@gruns is going to follow up with subvisual today to ensure the invite code ships

**Comment by reidlw** [comment]
Still are blocked on invite code; @gruns and @guanzo both trying to coordinate with Subvisual to get the code.

Subvisual is going to work on the code input box

**Comment by reidlw** [comment]
We using the milestone as a the collective tracking item for landing all the beta/mvp work. Can close this.
