### ISSUE TITLE
Create plan for network sharpening

### ISSUE THREAD

**Issue by prodalex** [filecoin-saturn/roadmap#30]

**Comment by prodalex** [comment]
@DiegoRBaquero to add link to first draft plan

**Comment by DiegoRBaquero** [comment]
https://www.notion.so/Saturn-improvements-a9032208f6234c1bb9943f6f3341e7ef

**Comment by prodalex** [comment]
@hannahhoward to review the plan and break down into tasks

**Comment by hannahhoward** [comment]
I'm going to start a new doc to finish this one.

**Comment by reidlw** [comment]
ETA for draft/review is EOD today; let's plan on reviewing and having plan aligned by Tuesday next week (10/10)

**Comment by hannahhoward** [comment]
Considering this done as https://www.notion.so/pl-strflt/Network-Sharpening-Plan-d33274f1de7e4715840f8e420a82ec19 is complete and feedback has been given, and it's been incorporated to a large extent into lab week planning.
