### ISSUE TITLE
[METERING] Create User Schema in DB

### ISSUE THREAD

**Issue by tchardin** [filecoin-saturn/roadmap#32]
- [x] Create a new table for user accounts, the user object should look like:
```json
{
  "id": "UUID",
  "email": "joe@company.com",
  "integrations": [
    {
    "id": "UUID",
    "user_id": "UUID",
    "name": "My awesome integration",
    "allow_list": ["company.com", "bucket.company.com"],
    "status": "active",
    "client_key": "jjdwekjdkwe"
    }
  ],
  "usage": [{
        "integration_id": "UUID",
  	"date": "datestring",
  	"requests": 100,
  	"bandwidth": 300,
  }]
}
```
- [x] Make sure the db has public endpoint with auth credentials for Subvisual
- [x] Use staging environment

**Comment by tchardin** [comment]
Subvisual have DB access and the schema but facing issues connecting.

**Comment by guanzo** [comment]
Gah. We either need to whitelist their IP or give them SSH tunnel access through our bastion host. Waiting for their response.

**Comment by guanzo** [comment]
Done!
