### ISSUE TITLE
[PARENT] Network Node Health V0

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-saturn/roadmap#40]
TODO:

- [ ] https://github.com/filecoin-saturn/orchestrator/pull/219
- [ ]  #47 
- [x] #54

**Comment by reidlw** [comment]
This ticket to be a top-level capture of network node health improvements before lab week. Hannah doesn't think there will be many more to add here

**Comment by hannahhoward** [comment]
Leaving open but we have rolled out the multinode and there's not much left to do.

**Comment by hannahhoward** [comment]
putting #47 , which is design not coding work -- for work to be done.

**Comment by reidlw** [comment]
@hannahhoward I'm at a little bit of a loss what to do with this one. I think maybe we don't need this parent and just deal with the child issues in our new prioritization process?

**Comment by reidlw** [comment]
No response, closing.
