### ISSUE TITLE
Deploy portal to staging and prod

### ISSUE THREAD

**Issue by reidlw** [filecoin-saturn/roadmap#51]

**Comment by reidlw** [comment]
@tchardin is working with subvisual on finalizing things before contract ends, then he's going to reach out to @joaosa to work on deployment to AWS

**Comment by gruns** [comment]
[portal](https://github.com/filecoin-saturn/portal) code committed and now ready for you to kick the tires, light the fires, and deploy to AWS, @joaosa, with @tchardin's help 🙌

**Comment by reidlw** [comment]
With Joao out today, @guanzo and @tchardin are going to pair up to try to get this done.

**Comment by guanzo** [comment]
Staging instance is live: https://portal.saturn-test.network/

For prod:
* Someone needs to fill out the business details (bank account, etc) on Stripe before we can receive the production API keys 
   * https://dashboard.stripe.com/account/onboarding/business-structure
   * Stripe login credentials are in 1Password under "Stripe Dashboard"
* AWS SES (Simple Email Service) needs to be setup.
  * Should we use an email other than `saturn@protocol.ai` for the portal? For emails that are sent by the portal, the email that we display to customers, etc. `saturn@protocol.ai` is already spammed with a ton of emails.

**Comment by reidlw** [comment]
> Staging instance is live: https://portal.saturn-test.network/
> 
> For prod:
> 
> * Someone needs to fill out the business details (bank account, etc) on Stripe before we can receive the production API keys
>   
>   * https://dashboard.stripe.com/account/onboarding/business-structure
>   * Stripe login credentials are in 1Password under "Stripe Dashboard"
> * AWS SES (Simple Email Service) needs to be setup.
>   
>   * Should we use an email other than `saturn@protocol.ai` for the portal? For emails that are sent by the portal, the email that we display to customers, etc. `saturn@protocol.ai` is already spammed with a ton of emails.

1. @gruns will help with the Stripe stuff; this is bound up in a larger conversation with legal he's currently engaged in.
2. we're going to use saturn@protocol.ai

**Comment by reidlw** [comment]
Per @guanzo this is going to get deployed to prod today

**Comment by guanzo** [comment]
Can't get prod stripe key without 2FA code

**Comment by reidlw** [comment]
I don't feel this is adding much value as a tracking issue, so I'm closing.
