### ISSUE TITLE
Update homepage/website to sell to both customers and node ops

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-saturn/roadmap#52]

**Comment by gruns** [comment]
[WIP design and copy](https://www.notion.so/pl-strflt/Copy-review-e1b84b9f8fdb40dbbb8feca4f8e4c46f), created by subvisual and drafted by alex for the portal, which will be turned repurposed to homepage design + copy

- [ ] @gruns: review copy
- [ ] @gruns: repurpose and finalize design for the homepage
- [ ] @guanzo: implement the design + copy into the website

**Comment by guanzo** [comment]
Left some comments on the notion doc, please advise. https://www.notion.so/pl-strflt/Copy-review-e1b84b9f8fdb40dbbb8feca4f8e4c46f

**Comment by reidlw** [comment]
Calling this done. We're tracking stuff moving forwards with more granular issues.
