### ISSUE TITLE
Don't penalize new nodes for cache misses

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-saturn/roadmap#54]
## Description:
Noticed a pattern in our weight calculation for nodes that might be preventing us from discovering some of the better nodes on the network:
- When a new node currently joins, most of its initial requests will be cache misses. Hence it will have terrible cache hit ratio, and its TTFB recordings will all be high due to cache misses.
- This will result in that node getting really low weights because P95 TTFB and cache hit ratio are two of the core measurements we use to determine weight.
- The node gets stuck in the following cycle: barely any requests -> almost 0 cache hit rate -> terrible ttfb -> low weight -> barely any requests -> repeat

**Comment by AmeanAsad** [comment]
- https://github.com/filecoin-saturn/orchestrator/pull/227: This PR targets this with a naive approach of just ignoring cache miss TTFB for bias weightings.

**Comment by DiegoRBaquero** [comment]
The penalty for new nodes is constrained by the days it's been active.
